---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: shop-os-dev
description: Custom automotive shop workstation operating system.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - btop
        - smartmontools
        - nvme-cli
        - lm_sensors
        - ethtool
        - pciutils
        - usbutils
        - openssh-server
        - python3-pyside6
        - plymouth
        - plymouth-plugin-script
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.chromium.Chromium
          - org.libreoffice.LibreOffice
          - org.kde.okular
          - org.kde.gwenview
          - com.rustdesk.RustDesk
      - scope: user

  - type: script
    scripts:
      - configure-boot.sh
      - install-epson-driver.sh

  - type: initramfs

  - type: signing
